package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class CounterStrike16 implements ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "376030");
        System.out.println(installedSuccessfully
                ? "Finished installing Ark Survival Evolved server. Start it with the -s flag."
                : "Failed installing Ark Survival Evolved server. See above for errors generated by SteamCMD.");
        System.out.println();
    }

}
