package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

public class ArmA3 extends ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "233780");
        System.out.println(installedSuccessfully
                ? "Finished installing ArmA 3 server. Start it with the -s flag."
                : "Failed installing ArmA 3. See above for errors generated by SteamCMD.");
    }

}
