package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")

public class CounterStrikeConditionZero extends ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "90");
        System.out.println(installedSuccessfully
                ? "Finished installing Counter-Strike: Condition Zero server. Start it with the -s flag."
                : "Failed installing Counter-Strike: Condition Zero server. See above for errors generated by SteamCMD.")
        ;
    }

    //TODO: !IMPORTANT! when creating start function for this game add +app_set_config "90 mod czero" for the game to work

}