package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class DontStarveTogether implements ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "343050");
        System.out.println(installedSuccessfully
                ? "Finished installing Don't Starve Together server. Start it with the -s flag."
                : "Failed installing Don't Starve Together server. See above for errors generated by SteamCMD.")
        ;
        System.out.println();
    }

}
