package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class NoMoreRoomInHell extends ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "317670");
        System.out.println(installedSuccessfully
                ? "Finished installing No More Room In Hell server. Start it with the -s flag."
                : "Failed installing No More Room In Hell server. See above for errors generated by SteamCMD.")
        ;
    }

}
