package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class SeriousSam3BFE extends ServerInstaller {
    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "41080");
        System.out.println(installedSuccessfully
                ? "Finished installing Serious Sam 3: BFE server. Start it with the -s flag."
                : "Failed installing Serious Sam 3: BFE server. See above for errors generated by SteamCMD.")
        ;
    }

}
