package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class SpaceEngineers extends ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "298740");
        System.out.println(installedSuccessfully
                ? "Finished installing Space Engineers server. Start it with the -s flag."
                : "Failed installing Space Engineers server. See above for errors generated by SteamCMD.")
        ;
    }

}
