package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

public class Starbound implements ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "211820");
        System.out.println(installedSuccessfully
                ? "Finished installing Starbound server. Start it with the -s flag."
                : "Failed installing Starbound server. See above for errors generated by SteamCMD.")
        ;
    }

}