package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.ServerInstaller;
import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

public class SvenCoop implements ServerInstaller {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "276060");
        System.out.println(installedSuccessfully
                ? "Finished installing Sven Co-op server. Start it with the -s flag."
                : "Failed installing Sven Co-op server. See above for errors generated by SteamCMD.")
        ;
    }

}