package com.gameservermanagers.JavaGSM.servers;

import com.gameservermanagers.JavaGSM.util.SteamcmdUtil;

import java.io.File;

@SuppressWarnings("unused")
public class TeamFortress2 {

    public static void install(File destination) {
        boolean installedSuccessfully = SteamcmdUtil.installApp("anonymous", destination, "232250");
        System.out.println(installedSuccessfully
                ? "Finished installing Team Fortress 2 server. Start it with the -s flag."
                : "Failed installing Team Fortress 2 server. See above for errors generated by SteamCMD.")
        ;
        System.out.println();
    }

}
